# Ruff configuration file
# Target Python 3.10+ (adjust based on your requirements)
target-version = "py310"

# Line length (PEP 8 standard)
line-length = 88

# Files to exclude from linting
exclude = [
    ".git",
    "__pycache__",
    "*.egg-info",
    ".venv",
    "venv",
    "build",
    "dist",
]

[lint]
# Enable specific rule categories
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings  
    "F",    # pyflakes
    "I",    # isort (import sorting)
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "PIE",  # flake8-pie
    "SIM",  # flake8-simplify
]

# Ignore specific rules that are less critical or harder to fix
ignore = [
    "E402",  # Module level import not at top of file (common in your codebase)
    "E501",  # Line too long (will be handled gradually)
    "E701",  # Multiple statements on one line (colon) - can be fixed later
    "F841",  # Local variable assigned but never used - can be cleaned up gradually
    "E722",  # Do not use bare except - should be fixed but not blocking
]

# Per-file ignores
[lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]
# Be more lenient with test files
"test_*.py" = ["F401", "F841"]
"*_test.py" = ["F401", "F841"]

# Configure isort
[lint.isort]
# Group imports properly
known-first-party = ["poker", "scene_setup", "utils", "src", "evaluation_pipeline", "chess", "diagnostic", "Noise"]

# Configure mccabe
[lint.mccabe]
# Maximum complexity for functions
max-complexity = 12 